apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"   # install first
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.14.5   # use a current stable version
    helm:
      # useful for k3s single-node
      values: |
        speaker:
          tolerateMaster: true   
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true