apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thefridge111/k3s-forge.git
    path: apps/nginx
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /status
    - kind: ServiceAccount
      jsonPointers:
        - /secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
