apiVersion: v1
kind: Service
metadata:
  name: ollama-web-ingress
  namespace: ollama
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: ollama-web-ingress
    app.kubernetes.io/component: web-ingress
    app.kubernetes.io/part-of: ollama
spec:
  selector:
    app.kubernetes.io/name: ollama-web-ingress
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240
